name: Lint and Test

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22', '1.23' ]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          go get ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # Require: The version of golangci-lint to use.
          version: v1.54

      - name: Build
        run: make build

      - name: Test
        env:
          KUSAMOCHI_GITHUB_TOKEN: ${{ secrets.KUSAMOCHI_GITHUB_TOKEN }}
        run: go test -v ./...
